sudo: required
services: 
  - docker

before_install:
  - docker build -t 546268815/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 546268815/complex npm run test -- --watchAll=false

after_success:
  - docker build -t 546268815/multi-client ./client
  - docker build -t 546268815/multi-nginx ./nginx
  - docker build -t 546268815/multi-server ./server
  - docker build -t 546268815/multi-worker ./worker

  #push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 546268815/multi-client
  - docker push 546268815/multi-nginx
  - docker push 546268815/multi-server
  - docker push 546268815/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-285052684367"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
